"""new db

Revision ID: 751704e175af
Revises: cc19193fad24
Create Date: 2024-02-20 02:44:25.516415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751704e175af'
down_revision = 'cc19193fad24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
